### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by rikkertkoppes** [poelstra/mhub#1]
To customize the available nodes and bindings, create a copy of server.conf.json, edit it to your needs and start the server as:

    node start -- -c <config_filename>

(Note: passing custom arguments only works with a recent npm, tested with 2.4.1)

Should be `npm start  -- -c <config_filename>` no?

**Comment by poelstra** [comment]
You're correct. I'll update it!

Thanks for reporting :)

**Comment by rikkertkoppes** [comment]
Also, the following is *nix syntax

>In another terminal, run:
>
>   node dist/src/client -n blib -t my:topic -d '"topic data"'

For windows this would be (I kid you not):

    node dist/src/client -n blib -t my:topic -d """topic data"""

That's three " in a row, since a quote needs to be escaped with another quote

**Comment by poelstra** [comment]
Both issues solved in v0.2.1, as published on npm too.
