### ISSUE TITLE
verbose option is not documented

### ISSUE THREAD

**Issue by Jheronymus** [poelstra/mhub#10]
The verbose option you've added in version 0.3.3 is not documented. Perhaps add the hint that Windows command or powershell will have trouble dealing with lots of messages, so this could solve performance issues while testing.

**Comment by poelstra** [comment]
Thanks for reporting!

The option is now documented, including the note for Windows console.

Also, you can now specify a log level in the config file, and override it on the commandline.
Released in 0.6.0.
