### ISSUE TITLE
add silent option

### ISSUE THREAD

**Issue by Jheronymus** [poelstra/mhub#11]
Currently the _verbose_ option disables all the logging, including the more relevant information at start up (ie port, config file etc)
I'd suggest to rename the _verbose_ option to _silent_ and use the _verbose_ flag to only disable individual message logging.

**Comment by poelstra** [comment]
You can now specify a log level in the config file, e.g.:

```js
{
    "logging": "debug" // or: none, fatal, error, warning, info (default)
}
```
and override it on the commandline using the `-l` (or `--loglevel`) option.

Released in 0.6.0.
