### ISSUE TITLE
Installation problems, not quite sure what

### ISSUE THREAD

**Issue by rikkertkoppes** [poelstra/mhub#2]
You seem to intend to build before publishing to npm

    "prepublish": "npm run lint && npm run build && npm run test"

However, the dist directory is not in npm

trace for reference:

    C:\>npm install -g poelstra/mhub
    npm http GET https://registry.npmjs.org/yargs
    npm http GET https://registry.npmjs.org/ws
    npm http GET https://registry.npmjs.org/minimatch
    npm http GET https://registry.npmjs.org/node-uuid
    npm http GET https://registry.npmjs.org/express
    npm http 304 https://registry.npmjs.org/minimatch
    npm http 200 https://registry.npmjs.org/node-uuid
    npm http 200 https://registry.npmjs.org/yargs
    npm http GET https://registry.npmjs.org/yargs/-/yargs-1.3.3.tgz
    npm http 200 https://registry.npmjs.org/express
    npm http 200 https://registry.npmjs.org/yargs/-/yargs-1.3.3.tgz
    npm http 200 https://registry.npmjs.org/ws
    npm http GET https://registry.npmjs.org/ws/-/ws-0.7.1.tgz
    npm http 200 https://registry.npmjs.org/ws/-/ws-0.7.1.tgz
    npm http GET https://registry.npmjs.org/brace-expansion
    npm http 304 https://registry.npmjs.org/brace-expansion
    npm http GET https://registry.npmjs.org/bufferutil
    npm http GET https://registry.npmjs.org/utf-8-validate
    npm http GET https://registry.npmjs.org/escape-html
    npm http GET https://registry.npmjs.org/cookie
    npm http GET https://registry.npmjs.org/options
    npm http GET https://registry.npmjs.org/accepts
    npm http GET https://registry.npmjs.org/content-type
    npm http GET https://registry.npmjs.org/finalhandler
    npm http GET https://registry.npmjs.org/ultron
    npm http GET https://registry.npmjs.org/depd
    npm http GET https://registry.npmjs.org/etag
    npm http GET https://registry.npmjs.org/cookie-signature
    npm http GET https://registry.npmjs.org/debug
    npm http GET https://registry.npmjs.org/content-disposition
    npm http GET https://registry.npmjs.org/methods
    npm http GET https://registry.npmjs.org/parseurl
    npm http GET https://registry.npmjs.org/on-finished
    npm http GET https://registry.npmjs.org/merge-descriptors
    npm http GET https://registry.npmjs.org/fresh
    npm http GET https://registry.npmjs.org/proxy-addr
    npm http GET https://registry.npmjs.org/send
    npm http GET https://registry.npmjs.org/range-parser
    npm http GET https://registry.npmjs.org/qs
    npm http GET https://registry.npmjs.org/vary
    npm http GET https://registry.npmjs.org/serve-static
    npm http GET https://registry.npmjs.org/type-is
    npm http GET https://registry.npmjs.org/path-to-regexp
    npm http GET https://registry.npmjs.org/utils-merge
    npm http 200 https://registry.npmjs.org/escape-html
    npm http GET https://registry.npmjs.org/escape-html/-/escape-html-1.0.1.tgz
    npm http 200 https://registry.npmjs.org/cookie
    npm http 304 https://registry.npmjs.org/options
    npm http 304 https://registry.npmjs.org/accepts
    npm http 304 https://registry.npmjs.org/content-type
    npm http GET https://registry.npmjs.org/cookie/-/cookie-0.1.2.tgz
    npm http 200 https://registry.npmjs.org/finalhandler
    npm http 200 https://registry.npmjs.org/depd
    npm http 304 https://registry.npmjs.org/etag
    npm http GET https://registry.npmjs.org/finalhandler/-/finalhandler-0.3.4.tgz
    npm http 304 https://registry.npmjs.org/cookie-signature
    npm http 200 https://registry.npmjs.org/escape-html/-/escape-html-1.0.1.tgz
    npm http GET https://registry.npmjs.org/depd/-/depd-1.0.1.tgz
    npm http 200 https://registry.npmjs.org/debug
    npm http 304 https://registry.npmjs.org/content-disposition
    npm http 200 https://registry.npmjs.org/cookie/-/cookie-0.1.2.tgz
    npm http 200 https://registry.npmjs.org/methods
    npm http 200 https://registry.npmjs.org/parseurl
    npm http 304 https://registry.npmjs.org/on-finished
    npm http 304 https://registry.npmjs.org/merge-descriptors
    npm http 200 https://registry.npmjs.org/finalhandler/-/finalhandler-0.3.4.tgz
    npm http 304 https://registry.npmjs.org/fresh
    npm http 304 https://registry.npmjs.org/proxy-addr
    npm http 200 https://registry.npmjs.org/depd/-/depd-1.0.1.tgz
    npm http 304 https://registry.npmjs.org/send
    npm http 304 https://registry.npmjs.org/range-parser
    npm http 304 https://registry.npmjs.org/vary
    npm http 200 https://registry.npmjs.org/qs
    npm http 304 https://registry.npmjs.org/serve-static
    npm http 304 https://registry.npmjs.org/type-is
    npm http 304 https://registry.npmjs.org/path-to-regexp
    npm http 304 https://registry.npmjs.org/utils-merge
    npm http GET https://registry.npmjs.org/qs/-/qs-2.4.1.tgz
    npm http GET https://registry.npmjs.org/balanced-match
    npm http GET https://registry.npmjs.org/concat-map
    npm http 200 https://registry.npmjs.org/qs/-/qs-2.4.1.tgz
    npm http 304 https://registry.npmjs.org/balanced-match
    npm http 304 https://registry.npmjs.org/concat-map
    npm http 200 https://registry.npmjs.org/bufferutil
    npm http 200 https://registry.npmjs.org/utf-8-validate
    npm http 304 https://registry.npmjs.org/ultron
    npm http GET https://registry.npmjs.org/bufferutil/-/bufferutil-1.0.1.tgz
    npm http GET https://registry.npmjs.org/utf-8-validate/-/utf-8-validate-1.0.1.tgz
    npm http GET https://registry.npmjs.org/negotiator
    npm http GET https://registry.npmjs.org/mime-types
    npm http GET https://registry.npmjs.org/forwarded
    npm http GET https://registry.npmjs.org/ee-first
    npm http GET https://registry.npmjs.org/crc
    npm http GET https://registry.npmjs.org/ipaddr.js
    npm http GET https://registry.npmjs.org/media-typer
    npm http 200 https://registry.npmjs.org/bufferutil/-/bufferutil-1.0.1.tgz
    npm http 200 https://registry.npmjs.org/utf-8-validate/-/utf-8-validate-1.0.1.tgz
    npm http 304 https://registry.npmjs.org/mime-types
    npm http 304 https://registry.npmjs.org/negotiator
    npm http 304 https://registry.npmjs.org/forwarded
    npm http 304 https://registry.npmjs.org/media-typer
    npm http GET https://registry.npmjs.org/destroy
    npm http GET https://registry.npmjs.org/ms
    npm http GET https://registry.npmjs.org/mime
    npm http 304 https://registry.npmjs.org/ee-first
    npm http 200 https://registry.npmjs.org/ipaddr.js
    npm http 304 https://registry.npmjs.org/crc
    npm http 200 https://registry.npmjs.org/mime
    npm http GET https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-0.1.9.tgz
    npm http 304 https://registry.npmjs.org/ms
    npm http GET https://registry.npmjs.org/mime/-/mime-1.3.4.tgz
    npm http 304 https://registry.npmjs.org/destroy
    npm http 200 https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-0.1.9.tgz
    npm http 200 https://registry.npmjs.org/mime/-/mime-1.3.4.tgz
    npm http GET https://registry.npmjs.org/mime-db
    npm http GET https://registry.npmjs.org/nan
    npm http GET https://registry.npmjs.org/bindings
    npm http 200 https://registry.npmjs.org/mime-db
    npm http 200 https://registry.npmjs.org/bindings
    npm http 200 https://registry.npmjs.org/nan

    > bufferutil@1.0.1 install C:\Users\NLRJK0030\AppData\Roaming\npm\node_modules\mhub\node_modules\ws\node_modules\bufferutil
    > node-gyp rebuild

    C:\Users\NLRJK0030\AppData\Roaming\npm\node_modules\mhub\node_modules\ws\node_modules\bufferutil>node "E:\Programs\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js
    " rebuild
    Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
      bufferutil.cc
    C:\Users\NLRJK0030\.node-gyp\0.10.28\deps\v8\include\v8.h(179): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [C:\Users\NLRJK0030\AppData\
    Roaming\npm\node_modules\mhub\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcxproj]
              with
              [
                  T=v8::Object
              ]
         Creating library C:\Users\NLRJK0030\AppData\Roaming\npm\node_modules\mhub\node_modules\ws\node_modules\bufferutil\build\Release\bufferutil.lib and object C:\Users\NLRJK0030\AppData\Roaming\npm\n
      ode_modules\mhub\node_modules\ws\node_modules\bufferutil\build\Release\bufferutil.exp
      Generating code
      Finished generating code
      bufferutil.vcxproj -> C:\Users\NLRJK0030\AppData\Roaming\npm\node_modules\mhub\node_modules\ws\node_modules\bufferutil\build\Release\\bufferutil.node

    > utf-8-validate@1.0.1 install C:\Users\NLRJK0030\AppData\Roaming\npm\node_modules\mhub\node_modules\ws\node_modules\utf-8-validate
    > node-gyp rebuild

    C:\Users\NLRJK0030\AppData\Roaming\npm\node_modules\mhub\node_modules\ws\node_modules\utf-8-validate>node "E:\Programs\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gy
    p.js" rebuild
    Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
      validation.cc
    C:\Users\NLRJK0030\.node-gyp\0.10.28\deps\v8\include\v8.h(179): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [C:\Users\NLRJK0030\AppData\
    Roaming\npm\node_modules\mhub\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj]
              with
              [
                  T=v8::Object
              ]
         Creating library C:\Users\NLRJK0030\AppData\Roaming\npm\node_modules\mhub\node_modules\ws\node_modules\utf-8-validate\build\Release\validation.lib and object C:\Users\NLRJK0030\AppData\Roaming\n
      pm\node_modules\mhub\node_modules\ws\node_modules\utf-8-validate\build\Release\validation.exp
      Generating code
      Finished generating code
      validation.vcxproj -> C:\Users\NLRJK0030\AppData\Roaming\npm\node_modules\mhub\node_modules\ws\node_modules\utf-8-validate\build\Release\\validation.node
    C:\Users\NLRJK0030\AppData\Roaming\npm\mping -> C:\Users\NLRJK0030\AppData\Roaming\npm\node_modules\mhub\bin\mping
    C:\Users\NLRJK0030\AppData\Roaming\npm\mclient -> C:\Users\NLRJK0030\AppData\Roaming\npm\node_modules\mhub\bin\mclient
    C:\Users\NLRJK0030\AppData\Roaming\npm\mserver -> C:\Users\NLRJK0030\AppData\Roaming\npm\node_modules\mhub\bin\mserver
    mhub@0.2.1 C:\Users\NLRJK0030\AppData\Roaming\npm\node_modules\mhub
    ├── node-uuid@1.4.3
    ├── yargs@1.3.3
    ├── minimatch@2.0.4 (brace-expansion@1.1.0)
    ├── express@4.12.3 (merge-descriptors@1.0.0, escape-html@1.0.1, cookie@0.1.2, utils-merge@1.0.0, methods@1.1.1, cookie-signature@1.0.6, fresh@0.2.4, finalhandler@0.3.4, range-parser@1.0.2, content-typ
    e@1.0.1, parseurl@1.3.0, vary@1.0.0, content-disposition@0.5.0, serve-static@1.9.2, path-to-regexp@0.1.3, depd@1.0.1, qs@2.4.1, on-finished@2.2.0, debug@2.1.3, etag@1.5.1, send@0.12.2, proxy-addr@1.0.
    7, accepts@1.2.5, type-is@1.6.1)
    └── ws@0.7.1 (options@0.0.6, ultron@1.0.1, bufferutil@1.0.1, utf-8-validate@1.0.1)

    C:\>mserver

    module.js:340
        throw err;
              ^
    Error: Cannot find module '../dist/src/server'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (C:\Users\NLRJK0030\AppData\Roaming\npm\node_modules\mhub\bin\mserver:2:1)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Function.Module.runMain (module.js:497:10)

    C:\>

**Comment by poelstra** [comment]
Ah, sorry about that. It's a 'bug' in the Readme, which still tells you to install from github (`poelstra/mhub`), instead of from npm (just `mhub`).

The dist/ dir *is* in npm, just not in the git clone (run a `npm install` in the clone to get that filled out if you want).
